language: python
python:
  - "3.6.7"

notifications:
  email: false
  
# install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt


# run pytest and coveralls script
script:
  - pytest --cov=app tests/

# then post the results to coveralls
after_success:
  - coveralls